### ISSUE TITLE
"&mfs" step gives incorrect result on big endian for objects with >5 variables

### ISSUE THREAD

**Issue by zeldin** [berkeley-abc/abc#257]
This was originally reported against Yosys as YosysHQ/yosys#3993.

A [designed created with LiteX](https://github.com/pottendo/RVCop64-pottendo) containing a VexRiscv-SMP core with 64-bit databus was synthesized with the same yosys version on ppc64 and ppc64le, both with and without `abc9.nomfs`
With `abc9.nomfs` both ppc64 and ppc64 syntesize the same JSON, from which a working bitstream can be generated.
However, without `abc9.nomfs` different JSONs are generated on ppc64 and ppc64le, and only the one geneated by ppc64le can be turned into a working bitstream.

The reason is because `giaMfs.c` makes used of something referred to as "truth tables", which are really bit vectors.  Rather than using a portable opaque implementation of a bit vector, UCB have opted to create a non-portable non-opaque implementation.

The implementation uses a vector of limbs to represent a bit vector of arbitrary but constant length.  The limb containing a particular bit with number `n` is chosen as
```
limbs[n >> log2(limb_bits)]
```
To extract the bit from the limb by moving it to the LSB (as is done for example by `Abc_TtGetBit()`), an expression like
```
limb >> (n & (limb_bits-1))
```
is used.

So far this is standard fare.  The problem arises because the code accesses the same bit vector alternatingly with a limb size of 32 bits and 64 bits.  Because of how the indexing is constructed above, this gives a consistent view on little endian, but not on big endian.  Due to the periodic way small vectors are initialized, it seems to work by happy accident for vectors with 32 or less significant bits, but breaks on larger ones.

This can be fixed in two ways:

1.  Select one limb size to be the canonical limb size.
Accesses using this limb size can pick any indexing scheme, including the above, regardless of endianness.  However, accesses using the non-canonical limb size would need to take into account that the ordering of 32 bit limbs within 64 bit limbs differs between big and little endian.  Bit-parallel operations like AND and OR can ignore this difference (except for the special case of a vector consisting only of a single 32-bit limb, although this case could be eliminated by always allocating at least 64 bits), but code doing shifts of containing literal limb values which are not 32-bit periodic would need to be updated.

or

2. Modify the indexing depending on endianness to preserve a consistent view over different limb sizes.
There is of course nothing magical about little endian that makes the switching of limb size work, it's just that the indexing scheme has been constructed to make it work on little endian specifically.  Since the limb index is `n >> log2(limb_bits)`, it means that the bit with number 0 is stored in the _first_  (index 0) limb.  In order for the indexing to be consistent over limb size, it is therefore important that the bit with number 0 is also stored in the _first_ bit of the limb.  On little endian this means the LSB, but on big endian this is the MSB.  So with this arrangement, on big endian the code to move bit n into the LSB of the limb would become
```
limb >> ((~n) & (limb_bits-1))
```
instead, while
```
limb << ((n) & (limb_bits-1))
```
would move bit n to the MSB of the limb.
With this approach code does not need to care about the limb size, but any and all code which does shifts or which contains non-palindromic literal limb values would need updating.

Regardless of which of these approaches is chosen, the lack of abstraction in the code makes updating it a daunting task.  A good first step would probably be to increase the use of the abstractions that do exist.  For example, `Extra_PrintHex()` could easily have used `Abc_TtGetHex()`, but does not.  There are also multiple instances of the same constant truth tables, like the truth table `s_Truths6` in `utilTruth.h` which exists in verbatim copies in at least `giaTruth.c` and `giaMfs.c`...

**Comment by heshpdx** [comment]
@zeldin, please see if this was addressed by commit https://github.com/berkeley-abc/abc/commit/733fec3.

**Comment by zeldin** [comment]
Well, no.  While I haven't taken this to bitstream, I can see that using yosys 0.59.1 (which carries said abc commit) I still get different JSONs on LE and BE unless I enable `nomfs`.

I'd also like to contend that the approach of "sprinkle the code with byteswaps until it seems to work" is usually not the best one, especially from a maintainability perspective.  Going forward I'd encourage you to use endian agnostic abstractions instead.

**Comment by zeldin** [comment]
Although, now that I look a little closer, I can see that the JSON on BE is now the same both with and without `nomfs` so apparently there is something that disables mfs on BE apart from my own local patch to do so (which I removed before doing the test obviously).  I'll need to investigate further...

**Comment by zeldin** [comment]
Ah, now I see.  It's not that the mfs step is disabled, but rather that it crashes the abc process with SIGSEGV, so there is never any result from it to use, which makes yosys fall back to using the non-mfs:ed netlist.

Well, I guess segfaulting is better than producing an incorrect result at least.  The crash may or may not be related to the commit mentioned, but as long as it is there it is hard for me to declare the issue as resolved...  😉

**Comment by zeldin** [comment]
Here is a backtrace from the crash:

```
#0  abc::Kit_TruthIsConst0 (pIn=<optimized out>, nVars=<optimized out>)
    at src/bool/kit/kit.h:322
#1  abc::Kit_TruthIsop_rec (puOn=puOn@entry=0x1db6b9000000001, 
    puOnDc=puOnDc@entry=0x1db6b9000000001, nVars=nVars@entry=9, 
    pcRes=pcRes@entry=0x7ffffffec488, vStore=vStore@entry=0x101d1af10)
    at src/bool/kit/kitIsop.c:241
#2  0x0000000100bbe828 in abc::Kit_TruthIsop (
    puTruth=puTruth@entry=0x1db6b9000000001, nVars=nVars@entry=9, 
    vMemory=vMemory@entry=0x101d1af10, fTryBoth=fTryBoth@entry=0)
    at src/bool/kit/kitIsop.c:148
#3  0x00000001009ed9e4 in abc::Sfm_TruthToCnf (Truth=<optimized out>, 
    pTruth=0x1db6b9000000001, nVars=9, vCover=0x101d1af10, 
    vCnf=vCnf@entry=0x101d1af30) at src/opt/sfm/sfmCnf.c:128
#4  0x00000001009ee0d8 in abc::Sfm_CreateCnf (p=p@entry=0x1024bdce0)
    at src/opt/sfm/sfmCnf.c:180
#5  0x0000000100a09c3c in abc::Sfm_NtkConstruct (vFanins=0x0, 
    vFanins@entry=0x101b9c4a0, nPis=<optimized out>, nPos=<optimized out>, 
    vFixed=vFixed@entry=0x101ba3810, vEmpty=vEmpty@entry=0x1024eefb0, 
    vDenied=vDenied@entry=0x10245dba0, vTruths=vTruths@entry=0x10248c080, 
    vStarts=vStarts@entry=0x101b9c4c0, vTruths2=vTruths2@entry=0x101f174b0)
    at src/opt/sfm/sfmNtk.c:195
#6  0x0000000100fab150 in abc::Gia_ManExtractMfs (p=p@entry=0x102451020)
    at src/aig/gia/giaMfs.c:289
#7  0x0000000100faedc0 in abc::Gia_ManPerformMfs (p=0x102451020, 
    pPars=0x7ffffffecb38) at src/aig/gia/giaMfs.c:543
#8  0x00000001003ddadc in abc::Abc_CommandAbc9Mfs (pAbc=0x101b73200, 
    argc=<optimized out>, argv=<optimized out>) at src/base/abci/abc.c:53318
#9  0x000000010055b154 in abc::CmdCommandDispatch (
    pAbc=pAbc@entry=0x101b73200, pargc=pargc@entry=0x7ffffffecd38, 
    pargv=pargv@entry=0x7ffffffecd40) at src/base/cmd/cmdUtils.c:157
#10 0x0000000100552b30 in abc::Cmd_CommandExecute (
    pAbc=pAbc@entry=0x101b73200, 
    sCommand=sCommand@entry=0x7ffffffece18 "&mfs;\n")
    at src/base/cmd/cmdApi.c:210
#11 0x000000010054f788 in abc::CmdCommandSource (pAbc=0x101b73200, 
    argc=<optimized out>, argv=<optimized out>) at src/base/cmd/cmd.c:795
#12 0x000000010055b154 in abc::CmdCommandDispatch (
    pAbc=pAbc@entry=0x101b73200, pargc=pargc@entry=0x7fffffff4fb8, 
    pargv=pargv@entry=0x7fffffff4fc0) at src/base/cmd/cmdUtils.c:157
#13 0x0000000100552b30 in abc::Cmd_CommandExecute (
    pAbc=pAbc@entry=0x101b73200, 
    sCommand=sCommand@entry=0x101b72e10 "source /tmp/yosys-abc-ddkpiL/abc.script") at src/base/cmd/cmdApi.c:210
#14 0x00000001005ba884 in abc::Abc_RealMain (argc=<optimized out>, 
    argv=<optimized out>) at src/base/main/mainReal.c:332
#15 0x000000010005a310 in main (argc=<optimized out>, argv=<optimized out>)
    at src/base/main/main.c:11
```

The pointer `0x1db6b9000000001` is clearly bogus and the direct cause of the SIGSEGV.  `0x101db6b90` on the other hand looks like it would be a valid pointer.  So it seems like this pointer is the victim of wanton wordswapping.  Did I mention that sprinkling swaps throughout the code is a bad idea?  😆

**Comment by zeldin** [comment]
I fixed the SIGSEGV in #465.  With that fix I get the same result from my test input on both big and little endian.

For the record I still believe that this inplace swapping is a bad idea, especially from a maintainability perspective, and that it would be better to adopt one of the two approaches I suggested in first comment of this issue.  If you agree I could work on a PR to that effect...

**Comment by heshpdx** [comment]
@zeldin I think that's a good idea, but I'm not the maintainer. I'm just a co-traveler!

**Comment by petterreinholdtsen** [comment]
Any hope for any of the maintainers/developers to chime in on the topic?
